name: Verify

on: [ push ]

env:
  LEFTHOOK: 0

jobs:
  verify:
    uses: meza/shared-github-workflows/.github/workflows/default-node-npm-ci.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
        test: false
        node-version: "latest"
        junit-report-path: "reports/junit.xml"
        cobertura-report-path: "reports/coverage/cobertura-coverage.xml"
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    needs: [ verify ]
    if: needs.verify.outputs.new-release-published == 'true'
    name: Build binaries for ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: meza/action-setup-node-npm@main
        with:
          node-version: 18.13.0
          cache-name: ${{ needs.verify.outputs.cache-name }}
      - name: Set version
        run: npm version --no-git-tag-version ${{ needs.verify.outputs.new-release-version }}
      - name: "Build"
        run: npm run build && npm run build:prebuilds
      - name: "Test"
        run: npm run test
      - name: "Upload binaries"
        run: npm run upload ${{ secrets.GITHUB_TOKEN }}
  release:
    needs: [ verify, build ]
    if: needs.verify.outputs.new-release-published == 'true'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: meza/action-setup-node-npm@main
        with:
          node-version: 18.13.0
          cache-name: ${{ needs.verify.outputs.cache-name }}
      - name: "Build"
        run: npm run build
      - name: 🚀 Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
