name: Verify

on: [ push ]

env:
  LEFTHOOK: 0

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify
    steps:
      - name: "Install deps"
        run: sudo apt install -y gcc-multilib g++-multilib
      - uses: actions/checkout@v3
      - name: Set up node
        uses: meza/action-setup-node-npm@main
        with:
          node-version: latest
          cache-name: ${{ needs.verify.outputs.cache-name }}
      - name: "Build"
        run: npm run build
      - name: "Test"
        run: npm run test
  build:
    runs-on: [windows-latest, ubuntu-latest, macos-latest]
    needs: [ verify ]
    if: needs.verify.outputs.new-release-published == 'true'
    name: Build binaries for ${{ matrix.runs-on }}
    steps:
      - name: "Install deps"
        run: sudo apt install -y gcc-multilib g++-multilib
      - uses: actions/checkout@v3
      - name: Set up node
        uses: meza/action-setup-node-npm@main
        with:
          node-version: latest
          cache-name: ${{ needs.verify.outputs.cache-name }}
      - name: "Build"
        run: npm run build:gyp && npm run build:prebuilds
      - name: "Upload binaries"
        run: npm run upload ${{ secrets.GITHUB_TOKEN }}
  release:
    needs: [ verify, build ]
    if: needs.verify.outputs.new-release-published == 'true'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: "Install deps"
        run: sudo apt install -y gcc-multilib g++-multilib
      - uses: actions/checkout@v3
      - name: Set up node
        uses: meza/action-setup-node-npm@main
        with:
          node-version: latest
          cache-name: ${{ needs.verify.outputs.cache-name }}
      - name: "Build"
        run: npm run build
      - name: 🚀 Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
